// <auto-generated />
using System;
using GliwickiDzik.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GliwickiDzik.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191125190144_IntroduceExercisesAndTrainingPrograms")]
    partial class IntroduceExercisesAndTrainingPrograms
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("GliwickiDzik.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("TrainingProgramId");

                    b.HasKey("Id");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("GliwickiDzik.Models.TrainingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DaysOfWeek");

                    b.Property<string>("Name");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("GliwickiDzik.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GliwickiDzik.Models.Exercise", b =>
                {
                    b.HasOne("GliwickiDzik.Models.TrainingProgram")
                        .WithMany("Exercises")
                        .HasForeignKey("TrainingProgramId");
                });

            modelBuilder.Entity("GliwickiDzik.Models.TrainingProgram", b =>
                {
                    b.HasOne("GliwickiDzik.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
